title: ExpCGM
description: A framework for modeling galactic atmospheres
theme: just-the-docs

url: https://gmvoit.github.io/ExpCGM

logo: GalAt-SMLbanner_150x40p-Color.png

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


    
    
